a = input('enter first value:')
b = input('enter second value:')
print('addition=', a+b)
print('subtraction=', a-b)
print('multiplication=', a*b)
print('division=', a/b)
print('modulo division=', a%b)
print('exponential=', a**b)